In [1]:
import pandas as pd

In [13]:
ips = pd.read_csv('ips.csv')
lycee_pro = pd.read_csv('lycee_pro.csv')
specialites = pd.read_csv('specialites.csv')
valeur_ajoutee_gen = pd.read_csv('valeur_ajoutee_gen.csv', low_memory = False)
valeur_ajoutee_pro = pd.read_csv('valeur_ajoutee_pro.csv', low_memory = False)

In [16]:
display(ips)
display(lycee_pro)
display(specialites)
display(valeur_ajoutee_gen)
display(valeur_ajoutee_pro)

,rentree_scolaire,academie,code_du_departement,departement,uai,nom_de_l_etablissment,code_insee_de_la_commune,nom_de_la_commune,secteur,type_de_lycee,effectifs_voie_gt,effectifs_voie_pro,effectifs_ensemble_gt_pro,ips_voie_gt,ips_voie_pro,ips_ensemble_gt_pro,ecart_type_de_l_ips_voie_gt,ecart_type_de_l_ips_voie_pro
0,2022-2023,LYON,1,AIN,0010001W,LYCEE PROFESSIONNEL ALEXANDRE BERARD LYCEE DES...,1004,AMBERIEU EN BUGEY,public,LP,NaN,583.0,583.0,NaN,91.5,91.5,NaN,27.2
1,2022-2023,LYON,1,AIN,0010006B,LYCEE POLYVALENT SAINT EXUPERY LYCEE DES METIE...,1033,VALSERHONE,public,LPO,556.0,334.0,890.0,99.2,84.2,93.6,33.3,24.8
2,2022-2023,LYON,1,AIN,0010013J,LYCEE GENERAL LALANDE,1053,BOURG EN BRESSE,public,LEGT,1028.0,NaN,1028.0,123.0,NaN,123.0,34.7,NaN
3,2022-2023,LYON,1,AIN,0010016M,LYCEE POLYVALENT JOSEPH MARIE CARRIAT,1053,BOURG EN BRESSE,public,LPO,1362.0,335.0,1697.0,111.7,98.8,109.2,32.9,30.2
4,2022-2023,LYON,1,AIN,0010069V,LYCEE GENERAL ET TECHNOLOGIQUE PRIVE ENSEMBLE ...,1034,BELLEY,privé sous contrat,LEGT,250.0,NaN,250.0,115.8,NaN,115.8,27.5,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3595,2022-2023,ORLEANS-TOURS,28,EURE-ET-LOIR,0280687V,LYCEE PROFESSIONNEL PRIVE DE COUASNON LYCEE DE...,28134,DREUX,privé sous contrat,LP,NaN,307.0,307.0,NaN,93.0,93.0,NaN,24.0
3596,2022-2023,RENNES,29,FINISTERE,0290010D,LYCEE GENERAL DE L HARTELOIRE,29019,BREST,public,LEGT,370.0,NaN,370.0,118.0,NaN,118.0,37.9,NaN
3597,2022-2023,RENNES,29,FINISTERE,0290034E,LYCEE GENERAL ET TECHNOLOGIQUE JEAN MARIE LE BRIS,29046,DOUARNENEZ,public,LEGT,353.0,NaN,353.0,114.5,NaN,114.5,31.4,NaN
3598,2022-2023,RENNES,29,FINISTERE,0290051Y,LYCEE GENERAL ET TECHNOLOGIQUE TRISTAN CORBIERE,29151,MORLAIX,public,LEGT,764.0,NaN,764.0,112.3,NaN,112.3,33.8,NaN
3599,2022-2023,RENNES,29,FINISTERE,0290108K,LYCEE POLYVALENT DUPUY DE LOME,29019,BREST,public,LPO,161.0,432.0,593.0,101.1,84.7,89.1,29.6,25.6

,rentree_scolaire,academie_2020,academie_2020_lib_l,numero_d_etablissement,patronyme,adresse_condensee,code_postal,commune_d_implantation,commune_d_implantation_lib_l,commune_et_arrondissement,commune_et_arrondissement_lib_l,secteur_d_enseignement_lib_l,mef_bcp_11,mef_bcp_11_lib_l,mef_bcp_6,mef_bcp_6_lib_l,nombre_d_eleves_total,nombre_d_eleves_filles,nombre_d_eleves_garcons
0,2019,12,NANCY-METZ,0880064S,EMILE GALLE,E.GALLE R.A DEDECKER,88151,88465,CAPAVENIR VOSGES,88465,CAPAVENIR VOSGES,SECTEUR PUBLIC,23830033003,TLE PRO3 ACC.SOINS-S.PERS. OPT.A DOMICILE,238300,BAC PRO EN 3 ANS : TERMINALE PRO,26,24.0,2.0
1,2019,12,NANCY-METZ,0880064S,EMILE GALLE,E.GALLE R.A DEDECKER,88151,88465,CAPAVENIR VOSGES,88465,CAPAVENIR VOSGES,SECTEUR PUBLIC,23830033004,TLE PRO3 ACC.SOINS-S.PERS. OPT.EN STRUCTUR,238300,BAC PRO EN 3 ANS : TERMINALE PRO,43,40.0,3.0
2,2019,12,NANCY-METZ,0880101G,NOTRE DAME - SAINT JOSEPH,NOTRE DAME-ST JOSEPH R THIERS,88012,88160,EPINAL,88160,EPINAL,SECTEUR PRIVE,32211020008,1BTS2 TECHNICO-COMMERCIAL,322110,BTS EN 2 ANS : 1ERE ANNEE,30,4.0,26.0
3,2019,12,NANCY-METZ,0880120C,NOTRE DAME DE LA PROVIDENCE,N.D.LA PROVIDENCE 14 R PASTEUR,88100,88413,SAINT-DIE-DES-VOSGES,88413,SAINT-DIE-DES-VOSGES,SECTEUR PRIVE,23830032207,TLE PRO3 REAL.PR.IMPR.PLURI.OPTA.PR.GRAPH.,238300,BAC PRO EN 3 ANS : TERMINALE PRO,8,1.0,7.0
4,2019,12,NANCY-METZ,0880133S,JEANNE D'ARC,JEANNE D'ARC 1 AVENUE CHANZY,88600,88078,BRUYERES,88078,BRUYERES,SECTEUR PRIVE,23830034403,TLE PRO3 METIERS DE LA SECURITE,238300,BAC PRO EN 3 ANS : TERMINALE PRO,25,7.0,18.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
177795,2019,18,ORLEANS-TOURS,0280684S,NOTRE DAME,NOTRE DAME LES VAUX,28240,28354,SAINT-MAURICE-SAINT-GERMAIN,28354,SAINT-MAURICE-SAINT-GERMAIN,SECTEUR PRIVE,23830022105,TLE PRO3 BOULANGER-PATISSIER,238300,BAC PRO EN 3 ANS : TERMINALE PRO,14,4.0,10.0
177796,2019,18,ORLEANS-TOURS,0280684S,NOTRE DAME,NOTRE DAME LES VAUX,28240,28354,SAINT-MAURICE-SAINT-GERMAIN,28354,SAINT-MAURICE-SAINT-GERMAIN,SECTEUR PRIVE,23830033403,TLE PRO3 COMMERC. SERVICES EN RESTAURATION,238300,BAC PRO EN 3 ANS : TERMINALE PRO,7,1.0,6.0
177797,2019,18,ORLEANS-TOURS,0280687V,DE COUASNON,DE COUASNON 37 RUE DE MORONVAL,28100,28134,DREUX,28134,DREUX,SECTEUR PRIVE,23220031214,2CAP2 EMPLOYE COMMERCE MULTISPECIALITES,232200,CAP EN 2 ANS : 2EME ANNEE,11,2.0,9.0
177798,2019,18,ORLEANS-TOURS,0280687V,DE COUASNON,DE COUASNON 37 RUE DE MORONVAL,28100,28134,DREUX,28134,DREUX,SECTEUR PRIVE,23820033002,1RE PRO3 SERVICES PROXIMITE VIE LOCALE,238200,BAC PRO EN 3 ANS : 1ERE PRO,15,7.0,8.0
177799,2019,18,ORLEANS-TOURS,0280687V,DE COUASNON,DE COUASNON 37 RUE DE MORONVAL,28100,28134,DREUX,28134,DREUX,SECTEUR PRIVE,23830031202,TLE PRO3 COMMERCE,238300,BAC PRO EN 3 ANS : TERMINALE PRO,22,8.0,14.0

,rentree_scolaire,region_academique,academie,departement,commune,numero_etablissement,denomination,patronyme,secteur,effectif_total_en_premiere_generale,...,16_langues_litt_et_cultures_etra_et_r_mathematiques_sciences_de_la_vie_et_de_la_terre_filles,16_langues_litt_et_cultures_etra_et_r_mathematiques_sciences_de_la_vie_et_de_la_terre_garcons,17_hist_geo_geopolitique_sc_politiques_mathematiques_sciences_de_la_vie_et_de_la_terre_filles,17_hist_geo_geopolitique_sc_politiques_mathematiques_sciences_de_la_vie_et_de_la_terre_garcons,18_hist_geo_geopolitique_sc_politiques_langues_litt_et_cultures_etra_et_r_mathematiques_filles,18_hist_geo_geopolitique_sc_politiques_langues_litt_et_cultures_etra_et_r_mathematiques_garcons,autres_combinaisons_filles,autres_combinaisons_garcons,1087_educ_physique_pratique_cult_sportive_filles,1087_educ_physique_pratique_cult_sportive_garcons
0,2020,AUVERGNE-RHONE-ALPES,CLERMONT-FERRAND,ALLIER,CUSSET,0030051P,LGT LYCEE DES METIERS,ALBERT LONDRES,PUBLIC,378,...,0,0,0,0,0,0,19,9,NaN,NaN
1,2020,AUVERGNE-RHONE-ALPES,CLERMONT-FERRAND,ALLIER,MONTLUCON,0030025L,LYCEE GENERAL,MADAME DE STAEL,PUBLIC,350,...,1,0,3,0,0,0,81,36,NaN,NaN
2,2020,AUVERGNE-RHONE-ALPES,CLERMONT-FERRAND,CANTAL,AURILLAC,0150646W,LYCEE GENERAL,EMILE DUCLAUX,PUBLIC,231,...,1,0,1,0,4,1,31,15,NaN,NaN
3,2020,AUVERGNE-RHONE-ALPES,CLERMONT-FERRAND,CANTAL,MAURIAC,0150747F,LPO LYCEE DES METIERS,NaN,PUBLIC,50,...,0,0,0,0,0,0,9,1,NaN,NaN
4,2020,AUVERGNE-RHONE-ALPES,CLERMONT-FERRAND,CANTAL,SAINT-FLOUR,0150030B,LYCEE POLYVALENT,DE HAUTE AUVERGNE,PUBLIC,127,...,1,3,1,3,0,1,19,1,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4495,2020,GRAND EST,NANCY-METZ,MOSELLE,METZ,0570057C,LYCEE GENERAL ET TECHNOLOGIQUE,ROBERT SCHUMAN,PUBLIC,158,...,3,2,1,10,1,1,25,9,NaN,NaN
4496,2020,GRAND EST,NANCY-METZ,VOSGES,MIRECOURT,0880036L,LYCEE GENERAL ET TECHNOLOGIQUE,JEAN-BAPTISTE VUILLAUME,PUBLIC,142,...,1,0,2,4,0,0,12,2,NaN,NaN
4497,2020,GRAND EST,NANCY-METZ,VOSGES,REMIREMONT,0880153N,LPO LYCEE DES METIERS,FILIERE BOIS ANDRE MALRAUX,PUBLIC,201,...,2,0,0,1,4,1,14,11,NaN,NaN
4498,2020,GRAND EST,REIMS,ARDENNES,CHARLEVILLE-MEZIERES,0080027L,LYCEE GENERAL ET TECHNOLOGIQUE,MONGE,PUBLIC,96,...,0,0,0,1,0,0,7,7,NaN,NaN
4499,2020,GRAND EST,REIMS,ARDENNES,REVIN,0080040A,LYCEE POLYVALENT,JEAN MOULIN,PUBLIC,62,...,0,2,0,0,1,1,2,1,NaN,NaN

,etablissement,annee,ville,code_etablissement,commune,academie,departement,secteur_public_pu_prive_pr,effectif_presents_serie_l,effectif_presents_serie_es,...,taux_men_brut_gnle,va_men_gnle,nombre_de_mentions_tb_avec_felicitations_g,nombre_de_mentions_tb_sans_felicitations_g,nombre_de_mentions_b_g,nombre_de_mentions_ab_g,nombre_de_mentions_tb_avec_felicitations_t,nombre_de_mentions_tb_sans_felicitations_t,nombre_de_mentions_b_t,nombre_de_mentions_ab_t
0,LYCEE ROLLINAT,2012,ARGENTON SUR CREUSE,0360002G,36006,ORLEANS-TOURS,INDRE,public,12.0,20.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,LYCEE SAINT GILLES (GENERAL ET TECHNO.),2012,VEIGNE,0371184L,37266,ORLEANS-TOURS,INDRE ET LOIRE,privé sous contrat,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,LYCEE JEAN MONNET,2012,JOUE LES TOURS,0371417P,37122,ORLEANS-TOURS,INDRE ET LOIRE,public,45.0,139.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,LYCEE ISER - BORDIER,2012,GRENOBLE,0380018N,38185,GRENOBLE,ISERE,privé sous contrat,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,LYCEE DE LA MATHEYSINE (GENERAL ET TECHNO.),2012,LA MURE D ISERE,0380049X,38269,GRENOBLE,ISERE,public,17.0,17.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25495,LYCEE JEAN MONNET,2015,STRASBOURG,0670078W,67482,STRASBOURG,BAS RHIN,public,33.0,65.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25496,LYCEE STANISLAS (GENERAL ET TECHNO.),2015,WISSEMBOURG,0670114K,67544,STRASBOURG,BAS RHIN,public,25.0,85.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25497,INSTITUTION STE PHILOMENE,2015,HAGUENAU,0671602C,67180,STRASBOURG,BAS RHIN,privé sous contrat,NaN,23.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25498,INSTIT.LA DOCTRINE CHRETIENNE,2015,STRASBOURG,0671611M,67482,STRASBOURG,BAS RHIN,privé sous contrat,11.0,20.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25499,INSTITUTION SAINTE CLOTILDE,2015,STRASBOURG,0671639T,67482,STRASBOURG,BAS RHIN,privé sous contrat,NaN,29.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

,etablissement,code_etablissement,annee,ville,commune,academie,departement,secteur_public_1_prive_2,effectifs_presents_specialites_pluri_technologiques,effectifs_presents_transformations,...,va_men_pluri_serv,va_men_echanges,va_men_communication,va_men_serv_pers,va_men_serv_collec,va_men_services,va_men_total,nombre_de_mentions_tb_sans_felicitations_p,nombre_de_mentions_b_p,nombre_de_mentions_ab_p
0,LYCEE PROFESSIONNEL MARCEL DEPREZ,0750788Z,2016,PARIS 11,75111,PARIS,PARIS,public,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,LYCEE PORTE OCEANE (PROFESSIONNEL),0760054W,2016,LE HAVRE,76351,NORMANDIE,SEINE MARITIME,public,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,LYCEE PROFESSIONNEL URUGUAY FRANCE,0770919F,2016,AVON,77014,CRETEIL,SEINE ET MARNE,public,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,LYCEE PROFESSIONNEL JULES FERRY,0770924L,2016,COULOMMIERS,77131,CRETEIL,SEINE ET MARNE,public,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,LYCEE PROFESSIONNEL PIERRE DE COUBERTIN,0770932V,2016,MEAUX,77284,CRETEIL,SEINE ET MARNE,public,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22295,LYCEE PROFESSIONNEL EDMOND LABBE,0690129R,2015,OULLINS,69149,LYON,RHONE,public,NaN,19.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22296,LYCEE PROFESSIONNEL NOTRE DAME,0691465T,2015,GIVORS,69091,LYON,RHONE,privé sous contrat,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22297,LYCEE PROFESSIONNEL FRANCOIS CEVERT,0693095P,2015,ECULLY,69081,LYON,RHONE,public,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22298,LYCEE PROFESSIONNEL DON BOSCO,0693371P,2015,LYON 05,69385,LYON,RHONE,privé sous contrat,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22299,LYCEE PROFESSIONNEL O R T,0693406C,2015,LYON 08,69388,LYON,RHONE,privé sous contrat,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN